-- PURBALINK Video production schema — D1
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS video_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, sort_order INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS creators (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, username TEXT NOT NULL UNIQUE, avatar_url TEXT, bio TEXT, verified INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS videos (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT DEFAULT '', category_id INTEGER, creator_id INTEGER, video_key TEXT NOT NULL, video_url TEXT, thumbnail_key TEXT, thumbnail_url TEXT, duration_seconds INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','review','scheduled','published','archived')), visibility TEXT NOT NULL DEFAULT 'public' CHECK(visibility IN ('public','unlisted','private')), featured INTEGER NOT NULL DEFAULT 0, trending INTEGER NOT NULL DEFAULT 0, views_count INTEGER NOT NULL DEFAULT 0, likes_count INTEGER NOT NULL DEFAULT 0, comments_count INTEGER NOT NULL DEFAULT 0, published_at TEXT, scheduled_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES video_categories(id) ON DELETE SET NULL, FOREIGN KEY(creator_id) REFERENCES creators(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS idx_videos_status_published ON videos(status,published_at DESC);
CREATE INDEX IF NOT EXISTS idx_videos_category ON videos(category_id,status,published_at DESC);
CREATE INDEX IF NOT EXISTS idx_videos_trending ON videos(trending,status,views_count DESC);
CREATE TABLE IF NOT EXISTS video_views (id INTEGER PRIMARY KEY AUTOINCREMENT, video_id INTEGER NOT NULL, viewer_hash TEXT, watched_seconds INTEGER NOT NULL DEFAULT 0, completed INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_video_views_video ON video_views(video_id,created_at DESC);
CREATE TABLE IF NOT EXISTS video_likes (video_id INTEGER NOT NULL, user_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(video_id,user_id), FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS video_bookmarks (video_id INTEGER NOT NULL, user_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(video_id,user_id), FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS video_comments (id INTEGER PRIMARY KEY AUTOINCREMENT, video_id INTEGER NOT NULL, user_id TEXT NOT NULL, parent_id INTEGER, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'published' CHECK(status IN ('published','hidden','deleted')), likes_count INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE, FOREIGN KEY(parent_id) REFERENCES video_comments(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_video_comments_video ON video_comments(video_id,status,created_at DESC);
INSERT OR IGNORE INTO video_categories(name,slug,sort_order) VALUES ('Berita','berita',1),('Kuliner','kuliner',2),('Wisata','wisata',3),('Karier','karier',4),('UMKM','umkm',5),('Hiburan','hiburan',6);
